apiVersion: v1
kind: ConfigMap
metadata:
  name: ta-bot-config
  namespace: petrosa-apps
  labels:
    app: petrosa-ta-bot
data:
  nats_url: "nats://nats-server:4222"
  api_endpoint: "http://api-server:8080/signals"
  log_level: "INFO"
  environment: "production"
  supported_symbols: "BTCUSDT,ETHUSDT,ADAUSDT"
  supported_timeframes: "15m,1h"
  rsi_period: "14"
  macd_fast: "12"
  macd_slow: "26"
  macd_signal: "9"
  adx_period: "14"
  bb_period: "20"
  bb_std: "2.0"
  atr_period: "14" 