apiVersion: apps/v1
kind: Deployment
metadata:
  name: petrosa-ta-bot
  namespace: petrosa-apps
  labels:
    app: petrosa-ta-bot
    version: latest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petrosa-ta-bot
  template:
    metadata:
      labels:
        app: petrosa-ta-bot
        version: VERSION_PLACEHOLDER
    spec:
      containers:
      - name: ta-bot
        image: yurisa2/petrosa-ta-bot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: NATS_URL
        - name: API_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: ta-bot-config
              key: api_endpoint
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: LOG_LEVEL
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: environment
        - name: SUPPORTED_SYMBOLS
          valueFrom:
            configMapKeyRef:
              name: ta-bot-config
              key: supported_symbols
        - name: SUPPORTED_TIMEFRAMES
          valueFrom:
            configMapKeyRef:
              name: ta-bot-config
              key: supported_timeframes
        - name: RSI_PERIOD
          valueFrom:
            configMapKeyRef:
              name: ta-bot-config
              key: rsi_period
        - name: MACD_FAST
          valueFrom:
            configMapKeyRef:
              name: ta-bot-config
              key: macd_fast
        - name: MACD_SLOW
          valueFrom:
            configMapKeyRef:
              name: ta-bot-config
              key: macd_slow
        - name: MACD_SIGNAL
          valueFrom:
            configMapKeyRef:
              name: ta-bot-config
              key: macd_signal
        - name: ADX_PERIOD
          valueFrom:
            configMapKeyRef:
              name: ta-bot-config
              key: adx_period
        - name: BB_PERIOD
          valueFrom:
            configMapKeyRef:
              name: ta-bot-config
              key: bb_period
        - name: BB_STD
          valueFrom:
            configMapKeyRef:
              name: ta-bot-config
              key: bb_std
        - name: ATR_PERIOD
          valueFrom:
            configMapKeyRef:
              name: ta-bot-config
              key: atr_period
        - name: NATS_ENABLED
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: NATS_ENABLED
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /live
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      restartPolicy: Always
      terminationGracePeriodSeconds: 30 